services:
  front_local:
    build:
      context: .
      dockerfile: local.dockerfile
    container_name: ${PROJECT_NAME}-front
    profiles:
      - local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    volumes:
      - ./front:/var/www
    ports:
      - "0.0.0.0:${WEB_PORT}:${APP_PORT:-80}/tcp"
    networks:
      - app-network
    healthcheck:
      test: wget --spider --no-verbose --tries=1 127.0.0.1:${APP_PORT:-80}/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 2

  redis:
    image: "redis:alpine"
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    profiles:
      - local
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge
